### ISSUE TITLE
Train Code

### ISSUE THREAD

**Issue by Frank-Dz** [JDAI-CV/DSD-SATN#7]
Hi! Thanks for your awesome work! Do you have any plans of sharing train code?

Thanks!

**Comment by Arthur151** [comment]
Thanks for your interest!
Yes, of course! But they won't be release in this repository. 
Limited by the licence agreement of some datasets and quoted codes, we may not provide the full training code.
Each essential module and useful tools for training will be released in other repositories of this github account.

**Comment by Frank-Dz** [comment]
Great! Thanks! But what time is it?

**Comment by lan786** [comment]
@Arthur151  What about for webcam part? We are waiting eagerly
