### ISSUE TITLE
difference between 'kps_alpha' and 'kp3d_mono' in human3.6m dataset

### ISSUE THREAD

**Issue by szlbiubiubiu** [JDAI-CV/DSD-SATN#8]
Hi, Nice work~

Can I ask which kps you used for training? I saw your code [https://github.com/JDAI-CV/DSD-SATN/blob/master/src/dataset/human36m_dataset.py](url)
You have used 'kps_alpha' to visualize the key-points. like the following figure:
![image](https://user-images.githubusercontent.com/35216645/82839612-da843780-9ec7-11ea-8709-c163a7681ec1.png)

But in your evaluation code, you utilize 'kp3d_mono' to do the evaluation. When I tried to visualize the 'kp3d_mono' by using your code, it seems the kp3d_mono is not aligned with the image:
![image](https://user-images.githubusercontent.com/35216645/82839669-0bfd0300-9ec8-11ea-8dd4-b3871afd9821.png)

Do you have any suggestion to visualize the 'kp3d_mono' in the right way?

**Comment by szlbiubiubiu** [comment]
Sorry I was wrong, I didn't pay attention to the evaluation had used 'kp2d'. 

Can I ask what is the difference from kp2d and kps_alpha?

**Comment by Arthur151** [comment]
Thanks for your interest! Let's see.
1. The kp2d is the ground truth 2D coordinates of keypoints, while the kps_alpha is estimated by the [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose).
2. About the frame extraction. I just drop the 0-th and the last frame that is not divisible by 5. It results in the 2 frames missing. Besides, please try to visualize the annotations to make sure.
The code of pre-processing is a mess. 
[h36m_preprocess.zip](https://github.com/JDAI-CV/DSD-SATN/files/4679691/h36m_preprocess.zip)
It is hard to find the frame extraction part.. maybe I just extract the frame by coding in console..

**Comment by szlbiubiubiu** [comment]
> Thanks for your interest! Let's see.
> 
> 1. The kp2d is the ground truth 2D coordinates of keypoints, while the kps_alpha is estimated by the [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose).
> 2. About the frame extraction. I just drop the 0-th and the last frame that is not divisible by 5. It results in the 2 frames missing. Besides, please try to visualize the annotations to make sure.
>    The code of pre-processing is a mess.
>    [h36m_preprocess.zip](https://github.com/JDAI-CV/DSD-SATN/files/4679691/h36m_preprocess.zip)
>    It is hard to find the frame extraction part.. maybe I just extract the frame by coding in console..

Thank you for your reply:)

It's clear to me about the extraction. I will try soon

**Comment by szlbiubiubiu** [comment]
Hi I am back again,

I have tried to build my model based on your dataloader, and meet some other problems.

Can I ask how was the evaluation result when you trained the model only using human3.6m without any other 2D dataset?

I currently only got 188 on MPJPE and 118 on PA_MPJPE.

**Comment by Arthur151** [comment]
I think there must be some thing wrong. The error should be half...
    	
    	

    	获取 Outlook for iOS
    
  




On Sat, May 30, 2020 at 8:02 PM +0800, "szlbiubiubiu" <notifications@github.com> wrote:















Hi I am back again,


I have tried to build my model based on your dataloader, and meet some other problems.


Can I ask how was the evaluation result when you trained the model only using human3.6m without any other 2D dataset?


I currently only got 188 on MPJPE and 118 on PA_MPJPE.
